[package]
name = "corvid_sim"
version = "0.1.0"
authors = ["trygve@stasjoner <trygve.woldseth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
backtrace = "0.3.46"